import { FormEvent, useMemo, useState } from 'react'
import { connections } from './data'
import { pillars, type Asset, type AssetStatus, type Pillar } from './domain'
import { loadAssets, saveAssets, statusLabel, updateAsset } from './store'

type Page = 'Overview' | 'Today’s Queue' | 'Content Library' | 'Character Bible' | 'Analytics' | 'Settings'
const pages: Page[] = ['Overview', 'Today’s Queue', 'Content Library', 'Character Bible', 'Analytics', 'Settings']
const formatDate = (date?: string) => date ? new Intl.DateTimeFormat('en-US', { month: 'short', day: 'numeric', year: 'numeric', hour: 'numeric', minute: '2-digit' }).format(new Date(date)) : '—'

function MediaTile({ asset, large = false }: { asset: Asset; large?: boolean }) {
  return <div className={`media-tile ${asset.pillar.toLowerCase().replaceAll(/[^a-z]/g, '-')} ${large ? 'large' : ''}`} aria-label={`${asset.title} visual preview`}>
    <div className="media-glow" /><span>{asset.mediaType === 'video' ? '▶ video concept' : '✦ image concept'}</span><strong>{asset.pillar}</strong><small>Demo visual proxy · canonical media pending</small>
  </div>
}
function Badge({ status }: { status: AssetStatus }) { return <span className={`badge ${status}`}>{statusLabel(status)}</span> }

export default function App() {
  const [page, setPage] = useState<Page>('Overview')
  const [assets, setAssets] = useState<Asset[]>(loadAssets)
  const [selected, setSelected] = useState<Asset | null>(null)
  const [toast, setToast] = useState('')
  const [query, setQuery] = useState(''); const [status, setStatus] = useState('all'); const [pillar, setPillar] = useState('all')
  const commit = (next: Asset[]) => { setAssets(next); saveAssets(next) }
  const change = (id: string, update: Partial<Asset>, message: string) => { const next = updateAsset(assets, id, update); commit(next); setSelected(next.find(a => a.id === id) || null); setToast(message) }
  const selectedFresh = selected ? assets.find(a => a.id === selected.id) || selected : null
  const filtered = useMemo(() => assets.filter(a => (status === 'all' || a.status === status) && (pillar === 'all' || a.pillar === pillar) && `${a.title} ${a.brief} ${a.provider} ${a.model} ${a.tags.join(' ')}`.toLowerCase().includes(query.toLowerCase())), [assets, query, status, pillar])
  const queue = assets.filter(a => a.status === 'awaiting_approval')
  const onImport = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const asset: Asset = { id: `import-${Date.now()}`, title: String(form.get('title') || 'Imported Higgsfield asset'), brief: String(form.get('brief') || 'Imported general-purpose adult creator media. Review before publishing.'), pillar: String(form.get('pillar')) as Pillar, status: 'awaiting_approval', provider: 'Higgsfield', model: String(form.get('model') || 'Unknown'), costUsd: null, caption: '', tags: ['#MilaVale'], createdAt: new Date().toISOString(), publishState: 'not_published', mediaType: 'image', sourceUrl: String(form.get('url') || ''), generationId: String(form.get('generationId') || ''), performance: { note: 'Imported locally; no live analytics connected.' } }; commit([asset, ...assets]); setToast('Higgsfield metadata imported into the local approval queue.'); event.currentTarget.reset() }
  return <div className="shell">
    <aside><div className="brand"><span>MV</span><div>Mila Vale<small>CONTROL CENTER</small></div></div><nav>{pages.map(item => <button key={item} className={page === item ? 'active' : ''} onClick={() => setPage(item)}>{item}</button>)}</nav><div className="approval-box"><span>● Approval required</span><p>Nothing publishes automatically.</p></div><div className="sidebar-foot">Mila Vale is a fictional, disclosed adult virtual creator.</div></aside>
    <main><header><div><p className="eyebrow">OPERATIONS / {page.toUpperCase()}</p><h1>{page === 'Overview' ? 'Good afternoon, Elliot.' : page}</h1></div><div className="header-state"><span className="demo-dot">●</span> Demo workspace <button onClick={() => setToast('Live provider connections are intentionally not enabled in this demo workspace.')}>Connection status</button></div></header>
      {toast && <div className="toast" role="status">{toast}<button onClick={() => setToast('')}>×</button></div>}
      {page === 'Overview' && <Overview assets={assets} queue={queue} onSelect={setSelected} onPage={setPage} />}
      {page === 'Today’s Queue' && <Queue assets={queue} onSelect={setSelected} onChange={change} />}
      {page === 'Content Library' && <Library assets={filtered} query={query} setQuery={setQuery} status={status} setStatus={setStatus} pillar={pillar} setPillar={setPillar} onSelect={setSelected} />}
      {page === 'Character Bible' && <Bible assets={assets} onSelect={setSelected} />}
      {page === 'Analytics' && <Analytics />}
      {page === 'Settings' && <Settings onImport={onImport} />}
    </main>
    {selectedFresh && <Detail asset={selectedFresh} close={() => setSelected(null)} onChange={change} />}
  </div>
}

function Overview({ assets, queue, onSelect, onPage }: { assets: Asset[]; queue: Asset[]; onSelect: (a: Asset) => void; onPage: (p: Page) => void }) { return <>
  <section className="hero"><div><span className="eyebrow">MILA VALE · V0.2</span><h2>Your approval-first content desk.</h2><p>Plan, review, and schedule general-purpose creator content. Live Fanvue data is not connected.</p><button className="primary" onClick={() => onPage('Today’s Queue')}>Review {queue.length} approval items →</button></div><div className="hero-card"><span>PIPELINE STATUS</span><strong>{queue.length} awaiting approval</strong><small>Generation → QC → Elliot approves → Schedule → Publish</small></div></section>
  <section className="metrics"><Metric label="Revenue" value="—" note="Demo · Fanvue not connected"/><Metric label="Active subscribers" value="—" note="Demo · Fanvue not connected"/><Metric label="Content ROI" value="—" note="Demo · attribution pending"/><Metric label="Assets tracked" value={String(assets.length)} note="Local demo workspace"/></section>
  <section className="split"><div className="panel"><div className="section-head"><div><p className="eyebrow">TODAY’S QUEUE</p><h2>Needs your eye</h2></div><button className="text-button" onClick={() => onPage('Today’s Queue')}>Open queue</button></div>{queue.map(a => <AssetRow asset={a} key={a.id} onSelect={onSelect}/>)}</div><div className="panel health"><p className="eyebrow">AUTOMATION HEALTH</p><h2>Safe to review</h2><Health name="Approval gate" value="Active" ok/><Health name="Fanvue publishing" value="Not connected"/><Health name="Higgsfield sync" value="Import ready"/><Health name="Analytics sync" value="Demo mode"/></div></section>
</> }
function Metric({ label, value, note }: { label: string; value: string; note: string }) { return <div className="metric"><p>{label}</p><strong>{value}</strong><small>{note}</small></div> }
function Health({ name, value, ok }: { name: string; value: string; ok?: boolean }) { return <div className="health-row"><span>{name}</span><b className={ok ? 'ok' : ''}>{ok ? '● ' : '○ '}{value}</b></div> }
function AssetRow({ asset, onSelect }: { asset: Asset; onSelect: (a: Asset) => void }) { return <button className="asset-row" onClick={() => onSelect(asset)}><MediaTile asset={asset}/><div><strong>{asset.title}</strong><p>{asset.pillar} · {asset.provider}</p></div><Badge status={asset.status}/><span className="chev">›</span></button> }
function Queue({ assets, onSelect, onChange }: { assets: Asset[]; onSelect: (a: Asset) => void; onChange: (id: string, u: Partial<Asset>, m: string) => void }) { return <section><div className="section-title"><p className="eyebrow">APPROVAL REQUIRED</p><h2>Today’s Queue</h2><p>Review media and metadata before any scheduling action.</p></div>{assets.length ? <div className="queue-grid">{assets.map(asset => <article className="content-card" key={asset.id}><button className="card-preview" onClick={() => onSelect(asset)}><MediaTile asset={asset}/></button><div className="card-body"><div><Badge status={asset.status}/><span className="date">{formatDate(asset.createdAt)}</span></div><button className="card-title" onClick={() => onSelect(asset)}>{asset.title}</button><p>{asset.caption}</p><div className="action-row"><button className="approve" onClick={() => onChange(asset.id, { status: 'approved' }, 'Asset approved. It remains unpublished until scheduled.')}>Approve</button><button onClick={() => onChange(asset.id, { status: 'rejected' }, 'Asset rejected and retained for audit history.')}>Reject</button><button onClick={() => onChange(asset.id, { status: 'draft' }, 'Regeneration request created as a draft. Connect Higgsfield to execute it.')}>Regenerate</button></div></div></article>)}</div> : <Empty title="Queue clear" text="There are no assets awaiting approval."/>}</section> }
function Library(props: { assets: Asset[]; query: string; setQuery: (s: string) => void; status: string; setStatus: (s: string) => void; pillar: string; setPillar: (s: string) => void; onSelect: (a: Asset) => void }) { return <section><div className="section-title"><p className="eyebrow">ASSET STORE</p><h2>Content Library</h2><p>Local demo metadata with provider-ready fields and persistent browser storage.</p></div><div className="filters"><input aria-label="Search content" placeholder="Search titles, briefs, tags, providers…" value={props.query} onChange={e => props.setQuery(e.target.value)}/><select value={props.status} onChange={e => props.setStatus(e.target.value)}><option value="all">All statuses</option>{['awaiting_approval','approved','rejected','scheduled','draft'].map(s => <option key={s} value={s}>{statusLabel(s as AssetStatus)}</option>)}</select><select value={props.pillar} onChange={e => props.setPillar(e.target.value)}><option value="all">All pillars</option>{pillars.map(p => <option key={p}>{p}</option>)}</select></div><div className="library-grid">{props.assets.map(a => <button className="library-card" onClick={() => props.onSelect(a)} key={a.id}><MediaTile asset={a}/><div><Badge status={a.status}/><h3>{a.title}</h3><p>{a.provider} · {a.model}</p></div></button>)}</div>{!props.assets.length && <Empty title="No matching content" text="Adjust the search or filters to see stored assets."/>}</section> }
function Bible({ assets, onSelect }: { assets: Asset[]; onSelect: (a: Asset) => void }) { return <section><div className="section-title"><p className="eyebrow">CANONICAL CHARACTER SYSTEM</p><h2>Mila Vale Character Bible</h2><p>Use these guardrails for every provider, prompt, QC review, and campaign.</p></div><div className="bible-grid"><Info title="Identity" items={['Mila Vale · age 24', 'Fictional, clearly disclosed AI / virtual creator', 'Gamer / tech / lifestyle creator', 'Adult-only fictional character; no real-person likeness']}/><Info title="Appearance rules" items={['Long dark brunette hair with soft natural waves', 'Hazel-green eyes; warm, lightly sun-kissed complexion', 'Athletic, healthy adult build; polished natural makeup', 'Subtle gold jewelry; premium contemporary styling']}/><Info title="Voice & tone" items={['Playful, confident, warm, conversational', 'Slightly nerdy and technology/gaming-aware', 'Natural and personable, never robotic', 'Transparent about virtual-creator identity where relevant']}/><Info title="Style & safety" items={['Premium photorealistic editorial look', 'Gaming room, gym, coffee, travel, city nightlife', 'General-purpose, non-explicit adult glamour only', 'Reject identity drift, youthfulness, or real-person resemblance']}/></div><div className="panel refs"><div className="section-head"><div><p className="eyebrow">CANONICAL REFERENCES</p><h2>Reference pack</h2></div><span className="notice">Not locked yet</span></div><p>Canonical Mila references have not been selected. Import approved Higgsfield candidate metadata in Settings after generation, then designate final references here.</p><div className="reference-list">{assets.slice(0, 3).map(a => <AssetRow key={a.id} asset={a} onSelect={onSelect}/>)}</div></div></section> }
function Info({ title, items }: { title: string; items: string[] }) { return <article className="info-card"><h3>{title}</h3><ul>{items.map(i => <li key={i}>{i}</li>)}</ul></article> }
function Analytics() { return <section><div className="section-title"><p className="eyebrow">MEASUREMENT</p><h2>Analytics</h2><p>Live Fanvue analytics are not connected yet. This view intentionally avoids invented business results.</p></div><div className="empty-analytics"><span>DEMO / EMPTY STATE</span><h3>Connect Fanvue to begin measurement.</h3><p>Once verified credentials and supported endpoints are configured, this area will display synchronized earnings, subscriber movement, publication performance, costs, and attribution confidence.</p><div><Metric label="Revenue" value="—" note="Awaiting source"/><Metric label="Conversion" value="—" note="Awaiting source"/><Metric label="Content ROI" value="—" note="Awaiting source"/></div></div></section> }
function Settings({ onImport }: { onImport: (e: FormEvent<HTMLFormElement>) => void }) { return <section><div className="section-title"><p className="eyebrow">CONFIGURATION</p><h2>Settings</h2><p>Connection states only—credentials remain in environment variables or deployment secret stores.</p></div><div className="connections">{connections.map(c => <article key={c.name} className="connection"><div><span className="connection-icon">{c.name.slice(0, 1)}</span><div><h3>{c.name}</h3><p>{c.role}</p></div></div><Badge status={'draft'}/><small>{c.detail}</small></article>)}</div><div className="settings-grid"><article className="panel"><p className="eyebrow">PUBLISHING MODE</p><h2>Approval required</h2><p>All publishing remains disabled until an asset has been explicitly approved and a verified Fanvue publisher adapter is connected.</p></article><form className="panel import" onSubmit={onImport}><p className="eyebrow">HIGGSFIELD IMPORT</p><h2>Add generation metadata</h2><p>Imports a URL/ID into the local approval queue. It does not call Higgsfield or publish content.</p><input required name="title" placeholder="Asset title"/><input name="generationId" placeholder="Higgsfield generation ID"/><input name="url" type="url" placeholder="Generation URL"/><select name="pillar" defaultValue="Gaming & Tech">{pillars.map(p => <option key={p}>{p}</option>)}</select><input name="model" placeholder="Model (optional)"/><textarea name="brief" placeholder="Prompt / generation brief"/><button className="primary">Import for review</button></form></div></section> }
function Empty({ title, text }: { title: string; text: string }) { return <div className="empty"><h3>{title}</h3><p>{text}</p></div> }
function Detail({ asset, close, onChange }: { asset: Asset; close: () => void; onChange: (id: string, u: Partial<Asset>, m: string) => void }) { const [caption, setCaption] = useState(asset.caption); const [date, setDate] = useState(asset.scheduledAt?.slice(0, 16) || ''); return <div className="modal-backdrop" role="presentation" onMouseDown={close}><section className="modal" role="dialog" aria-modal="true" aria-label={`${asset.title} details`} onMouseDown={e => e.stopPropagation()}><button className="close" onClick={close}>×</button><MediaTile asset={asset} large/><div className="modal-content"><div className="modal-heading"><div><Badge status={asset.status}/><h2>{asset.title}</h2></div><span>{asset.mediaType}</span></div><dl><div><dt>Content pillar</dt><dd>{asset.pillar}</dd></div><div><dt>Provider / model</dt><dd>{asset.provider} · {asset.model}</dd></div><div><dt>Generation cost</dt><dd>{asset.costUsd === null ? 'Not recorded' : `$${asset.costUsd.toFixed(2)}`}</dd></div><div><dt>Created</dt><dd>{formatDate(asset.createdAt)}</dd></div><div><dt>Scheduled</dt><dd>{formatDate(asset.scheduledAt)}</dd></div><div><dt>Publish state</dt><dd>{asset.publishState.replace('_', ' ')}</dd></div><div><dt>Generation ID</dt><dd>{asset.generationId || 'Not recorded'}</dd></div><div><dt>Performance</dt><dd>{asset.performance.note}</dd></div></dl><label>Prompt / generation brief<textarea value={asset.brief} readOnly /></label><label>Caption<textarea value={caption} onChange={e => setCaption(e.target.value)} /></label><div className="tags">{asset.tags.map(t => <span key={t}>{t}</span>)}</div><div className="modal-actions"><button onClick={() => onChange(asset.id, { caption }, 'Caption saved locally.')}>Save caption</button><button onClick={() => onChange(asset.id, { status: 'approved' }, 'Asset approved. It remains unpublished.')}>Approve</button><button onClick={() => onChange(asset.id, { status: 'rejected' }, 'Asset rejected and retained for audit history.')}>Reject</button></div><div className="schedule"><input aria-label="Schedule date" type="datetime-local" value={date} onChange={e => setDate(e.target.value)}/><button className="primary" onClick={() => date ? onChange(asset.id, { scheduledAt: new Date(date).toISOString(), status: 'scheduled', publishState: 'scheduled' }, 'Scheduled locally. Fanvue publishing remains disabled.') : undefined}>Schedule</button></div></div></section></div> }
