import { FormEvent, useMemo, useState } from 'react'
import { connections } from './data'
import { pillars, type Asset, type AssetStatus, type AssetType, type Pillar } from './domain'
import { higgsfieldElement, syncHiggsfieldManifest } from './services/higgsfield'
import { loadAssets, saveAssets, statusLabel, updateAsset } from './store'

type Page = 'Overview' | 'Today’s Queue' | 'Content Library' | 'Character Bible' | 'Analytics' | 'Settings'
const pages: Page[] = ['Overview', 'Today’s Queue', 'Content Library', 'Character Bible', 'Analytics', 'Settings']
const formatDate = (date: string | null) => date ? new Intl.DateTimeFormat('en-US', { month: 'short', day: 'numeric', year: 'numeric' }).format(new Date(date)) : 'Unknown'
const typeLabel = (type: AssetType) => type.replaceAll('_', ' ')
function MediaTile({ asset, large = false }: { asset: Asset; large?: boolean }) { const [broken, setBroken] = useState(false); const url = large ? asset.sourceUrl : asset.thumbnailUrl || asset.sourceUrl; return <div className={`media-tile real-media ${large ? 'large' : ''}`}>{!broken && <img src={url} alt={asset.title} onError={() => setBroken(true)}/>} {broken && <div className="media-fallback"><strong>Preview unavailable</strong><small>Saved Higgsfield URL could not be loaded.</small></div>}<span className="media-label">{typeLabel(asset.assetType)}</span></div> }
function Badge({ status }: { status: AssetStatus }) { return <span className={`badge ${status}`}>{statusLabel(status)}</span> }

export default function App() {
  const [page, setPage] = useState<Page>('Overview')
  const [assets, setAssets] = useState<Asset[]>(() => { const current = loadAssets(); const synced = syncHiggsfieldManifest(current); if (synced.imported) saveAssets(synced.assets); return synced.assets })
  const [selected, setSelected] = useState<Asset | null>(null); const [toast, setToast] = useState(''); const [query, setQuery] = useState(''); const [status, setStatus] = useState('all'); const [pillar, setPillar] = useState('all'); const [assetType, setAssetType] = useState('all')
  const commit = (next: Asset[]) => { setAssets(next); saveAssets(next) }
  const change = (id: string, update: Partial<Asset>, message: string) => { const next = updateAsset(assets, id, update); commit(next); setSelected(next.find(a => a.id === id) || null); setToast(message) }
  const sync = () => { const next = syncHiggsfieldManifest(assets); commit(next.assets); setToast(next.imported ? `Synced ${next.imported} Higgsfield assets.` : 'All known Higgsfield generations are already imported.') }
  const filtered = useMemo(() => assets.filter(a => (status === 'all' || a.status === status) && (pillar === 'all' || a.pillar === pillar) && (assetType === 'all' || a.assetType === assetType) && `${a.title} ${a.prompt || ''} ${a.provider} ${a.model || ''} ${a.tags.join(' ')}`.toLowerCase().includes(query.toLowerCase())), [assets, query, status, pillar, assetType])
  const queue = assets.filter(a => a.status === 'awaiting_approval' && a.assetType === 'launch_content')
  const onImport = (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const f = new FormData(e.currentTarget); const generationId = String(f.get('generationId') || '').trim(); if (assets.some(a => a.generationId === generationId)) return setToast('That Higgsfield generation ID is already imported.'); const url = String(f.get('url')); const asset: Asset = { id: `higgsfield-${generationId}`, generationId, reusableElementId: higgsfieldElement.id, assetType: 'launch_content', title: String(f.get('title') || 'Imported Higgsfield asset'), pillar: String(f.get('pillar')) as Pillar, prompt: String(f.get('prompt') || '') || null, provider: 'Higgsfield', model: String(f.get('model') || '') || null, sourceUrl: url, thumbnailUrl: String(f.get('thumbnailUrl') || '') || url, createdAt: new Date().toISOString(), costUsd: null, status: 'awaiting_approval', publishState: 'not_published', caption: '', tags: ['#MilaVale'], scheduledAt: null, fanvuePostId: null, performance: { note: 'Imported locally; no live analytics sync is connected.' } }; commit([asset, ...assets]); setToast('Higgsfield generation imported into the approval queue.'); e.currentTarget.reset() }
  const selectedFresh = selected ? assets.find(a => a.id === selected.id) || selected : null
  return <div className="shell"><aside><div className="brand"><span>MV</span><div>Mila Vale<small>CONTROL CENTER</small></div></div><nav>{pages.map(item => <button key={item} className={page === item ? 'active' : ''} onClick={() => setPage(item)}>{item}</button>)}</nav><div className="approval-box"><span>● Approval required</span><p>Nothing publishes automatically.</p></div><div className="sidebar-foot">Mila Vale is a fictional, disclosed adult virtual creator.</div></aside><main><header><div><p className="eyebrow">OPERATIONS / {page.toUpperCase()}</p><h1>{page === 'Overview' ? 'Good afternoon, Elliot.' : page}</h1></div><div className="header-state"><span className="demo-dot">●</span> Local asset store</div></header>{toast && <div className="toast" role="status">{toast}<button onClick={() => setToast('')}>×</button></div>}{page === 'Overview' && <Overview assets={assets} queue={queue} onSelect={setSelected} onPage={setPage}/>} {page === 'Today’s Queue' && <Queue assets={queue} onSelect={setSelected} onChange={change}/>} {page === 'Content Library' && <Library assets={filtered} query={query} setQuery={setQuery} status={status} setStatus={setStatus} pillar={pillar} setPillar={setPillar} assetType={assetType} setAssetType={setAssetType} onSelect={setSelected}/>} {page === 'Character Bible' && <Bible assets={assets} onSelect={setSelected}/>} {page === 'Analytics' && <Analytics/>} {page === 'Settings' && <Settings onImport={onImport} onSync={sync}/>}</main>{selectedFresh && <Detail asset={selectedFresh} close={() => setSelected(null)} onChange={change}/>}</div>
}
function Overview({ assets, queue, onSelect, onPage }: { assets: Asset[]; queue: Asset[]; onSelect: (a: Asset) => void; onPage: (p: Page) => void }) { return <><section className="hero"><div><span className="eyebrow">MILA VALE · V0.3</span><h2>Your approval-first content desk.</h2><p>Real Higgsfield generation records are local. Fanvue remains disconnected.</p><button className="primary" onClick={() => onPage('Today’s Queue')}>Review {queue.length} launch approval items →</button></div><div className="hero-card"><span>PIPELINE STATUS</span><strong>{queue.length} awaiting approval</strong><small>Generate → QC → Elliot approves → Schedule → Publish</small></div></section><section className="metrics"><Metric label="Revenue" value="—" note="Fanvue not connected"/><Metric label="Active subscribers" value="—" note="Fanvue not connected"/><Metric label="Content ROI" value="—" note="Attribution pending"/><Metric label="Assets tracked" value={String(assets.length)} note="Persistent local store"/></section><section className="split"><div className="panel"><div className="section-head"><div><p className="eyebrow">TODAY’S QUEUE</p><h2>Needs your eye</h2></div><button className="text-button" onClick={() => onPage('Today’s Queue')}>Open queue</button></div>{queue.length ? queue.slice(0, 3).map(a => <AssetRow asset={a} key={a.id} onSelect={onSelect}/>) : <Empty title="Queue clear" text="No launch assets await approval."/>}</div><div className="panel health"><p className="eyebrow">AUTOMATION HEALTH</p><h2>Safe to review</h2><Health name="Approval gate" value="Active" ok/><Health name="Higgsfield ingest" value="Manifest sync ready" ok/><Health name="Fanvue publishing" value="Not connected"/><Health name="Analytics sync" value="Empty state"/></div></section></> }
function Metric({ label, value, note }: { label: string; value: string; note: string }) { return <div className="metric"><p>{label}</p><strong>{value}</strong><small>{note}</small></div> }; function Health({ name, value, ok }: { name: string; value: string; ok?: boolean }) { return <div className="health-row"><span>{name}</span><b className={ok ? 'ok' : ''}>{ok ? '● ' : '○ '}{value}</b></div> }; function AssetRow({ asset, onSelect }: { asset: Asset; onSelect: (a: Asset) => void }) { return <button className="asset-row" onClick={() => onSelect(asset)}><MediaTile asset={asset}/><div><strong>{asset.title}</strong><p>{asset.pillar} · {asset.provider}</p></div><Badge status={asset.status}/><span className="chev">›</span></button> }
function Queue({ assets, onSelect, onChange }: { assets: Asset[]; onSelect: (a: Asset) => void; onChange: (id: string, u: Partial<Asset>, m: string) => void }) { return <section><div className="section-title"><p className="eyebrow">APPROVAL REQUIRED</p><h2>Today’s Queue</h2><p>Only launch content appears here; canonical references remain separate.</p></div>{assets.length ? <div className="queue-grid">{assets.map(a => <article className="content-card" key={a.id}><button className="card-preview" onClick={() => onSelect(a)}><MediaTile asset={a}/></button><div className="card-body"><div><Badge status={a.status}/><span className="date">{formatDate(a.createdAt)}</span></div><button className="card-title" onClick={() => onSelect(a)}>{a.title}</button><p>{a.caption || 'No caption yet — edit in asset details.'}</p><div className="action-row"><button className="approve" onClick={() => onChange(a.id, { status: 'approved' }, 'Asset approved. It remains unpublished until scheduled.')}>Approve</button><button onClick={() => onChange(a.id, { status: 'rejected' }, 'Asset rejected and retained locally.')}>Reject</button><button onClick={() => onChange(a.id, { status: 'draft', regenerationRequestedAt: new Date().toISOString() }, 'Regeneration request recorded. Higgsfield was not called.')}>Regenerate</button></div></div></article>)}</div> : <Empty title="Queue clear" text="There are no launch assets awaiting approval."/>}</section> }
function Library(p: { assets: Asset[]; query: string; setQuery: (s: string) => void; status: string; setStatus: (s: string) => void; pillar: string; setPillar: (s: string) => void; assetType: string; setAssetType: (s: string) => void; onSelect: (a: Asset) => void }) { return <section><div className="section-title"><p className="eyebrow">ASSET STORE</p><h2>Content Library</h2><p>Real Higgsfield media and metadata, persisted in this browser.</p></div><div className="filters"><input aria-label="Search content" placeholder="Search titles, prompts, tags, providers…" value={p.query} onChange={e => p.setQuery(e.target.value)}/><select value={p.status} onChange={e => p.setStatus(e.target.value)}><option value="all">All approval states</option>{['awaiting_approval','approved','rejected','scheduled','draft'].map(s => <option key={s} value={s}>{statusLabel(s as AssetStatus)}</option>)}</select><select value={p.pillar} onChange={e => p.setPillar(e.target.value)}><option value="all">All pillars</option>{pillars.map(x => <option key={x}>{x}</option>)}</select><select value={p.assetType} onChange={e => p.setAssetType(e.target.value)}><option value="all">All asset types</option>{(['canonical_anchor','reference','launch_content'] as AssetType[]).map(x => <option key={x} value={x}>{typeLabel(x)}</option>)}</select></div><div className="library-grid">{p.assets.map(a => <button className="library-card" onClick={() => p.onSelect(a)} key={a.id}><MediaTile asset={a}/><div><Badge status={a.status}/><h3>{a.title}</h3><p>{a.provider} · {a.model || 'Model unknown'}</p></div></button>)}</div>{!p.assets.length && <Empty title="No matching content" text="Adjust the search or filters to see stored assets."/>}</section> }
function Bible({ assets, onSelect }: { assets: Asset[]; onSelect: (a: Asset) => void }) { const canonical = assets.filter(a => a.assetType !== 'launch_content'); const launch = assets.filter(a => a.assetType === 'launch_content'); return <section><div className="section-title"><p className="eyebrow">CANONICAL CHARACTER SYSTEM</p><h2>Mila Vale Character Bible</h2><p>Canonical references are distinct from approval-queue launch content.</p></div><div className="bible-grid"><Info title="Identity" items={['Mila Vale · fictional adult age 24', 'Clearly disclosed AI / virtual creator', `Higgsfield element: ${higgsfieldElement.name}`, `Element ID: ${higgsfieldElement.id}`, `Status: ${higgsfieldElement.status}`]}/><Info title="Consistency rules" items={['Long dark brunette hair with soft waves', 'Hazel-green eyes and warm sun-kissed complexion', 'Athletic adult build; polished natural makeup', 'Premium, non-explicit creator editorial']}/></div><ReferencePanel title="Canonical / reference assets" text="Use these to protect Mila’s visual identity. They never enter the publishing queue automatically." assets={canonical} onSelect={onSelect}/><ReferencePanel title="Launch / content assets" text="Real media, still approval-first." assets={launch} onSelect={onSelect}/></section> }
function ReferencePanel({ title, text, assets, onSelect }: { title: string; text: string; assets: Asset[]; onSelect: (a: Asset) => void }) { return <div className="panel refs"><div className="section-head"><div><p className="eyebrow">HIGGSFIELD</p><h2>{title}</h2></div><span className="notice">{assets.length} imported</span></div><p>{text}</p><div className="reference-list">{assets.map(a => <AssetRow key={a.id} asset={a} onSelect={onSelect}/>)}</div></div> }; function Info({ title, items }: { title: string; items: string[] }) { return <article className="info-card"><h3>{title}</h3><ul>{items.map(i => <li key={i}>{i}</li>)}</ul></article> }
function Analytics() { return <section><div className="section-title"><p className="eyebrow">MEASUREMENT</p><h2>Analytics</h2><p>Live Fanvue analytics are not connected. This view intentionally avoids invented business results.</p></div><div className="empty-analytics"><span>EMPTY STATE</span><h3>Connect Fanvue to begin measurement.</h3><p>Source-verified publishing and analytics are required before this area can show earnings, subscribers, or performance.</p></div></section> }
function Settings({ onImport, onSync }: { onImport: (e: FormEvent<HTMLFormElement>) => void; onSync: () => void }) { return <section><div className="section-title"><p className="eyebrow">CONFIGURATION</p><h2>Settings</h2><p>Credentials remain outside this browser application.</p></div><div className="connections">{connections.map(c => <article key={c.name} className="connection"><div><span className="connection-icon">{c.name.slice(0, 1)}</span><div><h3>{c.name}</h3><p>{c.role}</p></div></div><small>{c.detail}</small></article>)}</div><div className="settings-grid"><article className="panel"><p className="eyebrow">HIGGSFIELD MANIFEST</p><h2>Known Mila assets</h2><p>Reads the repository’s structured Mila manifest and imports only generation IDs absent from the local browser store. It does not call Higgsfield.</p><button className="primary" onClick={onSync}>Sync Higgsfield assets</button></article><form className="panel import" onSubmit={onImport}><p className="eyebrow">ONE-GENERATION IMPORT</p><h2>Add a Higgsfield generation</h2><p>Unknown cost, analytics, and publish identifiers remain blank.</p><input required name="title" placeholder="Asset title"/><input required name="generationId" placeholder="Higgsfield generation ID"/><input required name="url" type="url" placeholder="Raw media URL"/><input name="thumbnailUrl" type="url" placeholder="Thumbnail URL (optional)"/><select name="pillar" defaultValue="Gaming & Tech">{pillars.map(x => <option key={x}>{x}</option>)}</select><input name="model" placeholder="Model (optional)"/><textarea name="prompt" placeholder="Prompt (optional)"/><button className="primary">Import for review</button></form></div></section> }
function Empty({ title, text }: { title: string; text: string }) { return <div className="empty"><h3>{title}</h3><p>{text}</p></div> }
function Detail({ asset, close, onChange }: { asset: Asset; close: () => void; onChange: (id: string, u: Partial<Asset>, m: string) => void }) { const [caption, setCaption] = useState(asset.caption); const [date, setDate] = useState(asset.scheduledAt?.slice(0,16) || ''); return <div className="modal-backdrop" onMouseDown={close}><section className="modal" role="dialog" aria-modal="true" onMouseDown={e => e.stopPropagation()}><button className="close" onClick={close}>×</button><MediaTile asset={asset} large/><div className="modal-content"><div className="modal-heading"><div><Badge status={asset.status}/><h2>{asset.title}</h2></div><span>{typeLabel(asset.assetType)}</span></div><dl><div><dt>Provider / model</dt><dd>{asset.provider} · {asset.model || 'Unknown'}</dd></div><div><dt>Generation ID</dt><dd>{asset.generationId}</dd></div><div><dt>Reusable element ID</dt><dd>{asset.reusableElementId || 'None recorded'}</dd></div><div><dt>Created</dt><dd>{formatDate(asset.createdAt)}</dd></div><div><dt>Cost</dt><dd>{asset.costUsd === null ? 'Unknown' : `$${asset.costUsd.toFixed(2)}`}</dd></div><div><dt>Fanvue post ID</dt><dd>{asset.fanvuePostId || 'Not published'}</dd></div></dl><label>Raw media URL<input value={asset.sourceUrl} readOnly/></label><label>Prompt<textarea value={asset.prompt || 'Not recorded by the source manifest.'} readOnly/></label><label>Caption<textarea value={caption} onChange={e => setCaption(e.target.value)}/></label><div className="tags">{asset.tags.map(t => <span key={t}>{t}</span>)}</div><div className="modal-actions"><button onClick={() => onChange(asset.id, { caption }, 'Caption saved locally.')}>Save caption</button><button onClick={() => onChange(asset.id, { status: 'approved' }, 'Asset approved. It remains unpublished.')}>Approve</button><button onClick={() => onChange(asset.id, { status: 'rejected' }, 'Asset rejected and retained locally.')}>Reject</button><button onClick={() => onChange(asset.id, { status: 'draft', regenerationRequestedAt: new Date().toISOString() }, 'Regeneration request recorded. Higgsfield was not called.')}>Regenerate</button></div>{asset.assetType === 'launch_content' && <div className="schedule"><input type="datetime-local" value={date} onChange={e => setDate(e.target.value)}/><button className="primary" onClick={() => date && onChange(asset.id, { scheduledAt: new Date(date).toISOString(), status: 'scheduled', publishState: 'scheduled' }, 'Scheduled locally. Fanvue remains disabled.')}>Schedule</button></div>}</div></section></div> }
