import type { Asset, ProviderConnection } from './domain'

export const initialAssets: Asset[] = [
  { id: 'mv-001', title: 'Midnight desk setup', brief: 'Clearly adult virtual creator Mila Vale in a premium RGB gaming room, midnight-blue palette, long brunette waves, hazel-green eyes, relaxed editorial pose; non-explicit lifestyle content.', pillar: 'Gaming & Tech', status: 'awaiting_approval', provider: 'Higgsfield', model: 'Soul', costUsd: 0.18, caption: 'Late-night patches and a little too much coffee. Which game owns your weekend? ✨', tags: ['#MilaVale', '#GamingSetup', '#VirtualCreator'], createdAt: '2026-08-30T13:40:00Z', publishState: 'not_published', mediaType: 'image', generationId: 'demo-hf-001', performance: { note: 'No live Fanvue data connected.' } },
  { id: 'mv-002', title: 'Golden-hour cooldown', brief: 'Adult virtual creator in a minimalist bright gym after a workout. Athletic healthy build, warm complexion, subtle gold jewelry, premium wellness editorial; non-explicit.', pillar: 'Fitness & Wellness', status: 'awaiting_approval', provider: 'Higgsfield', model: 'Soul', costUsd: 0.18, caption: 'A little movement changes the whole day. What are you training this week?', tags: ['#Wellness', '#GymDay', '#MilaVale'], createdAt: '2026-08-30T12:30:00Z', publishState: 'not_published', mediaType: 'image', generationId: 'demo-hf-002', performance: { note: 'No live Fanvue data connected.' } },
  { id: 'mv-003', title: 'Hotel lobby arrival', brief: 'Adult virtual creator Mila Vale in a contemporary hotel lobby, evening travel editorial, tailored black outfit and gold accents; clearly virtual creator and non-explicit.', pillar: 'Travel', status: 'scheduled', provider: 'Manual import', model: 'Metadata import', costUsd: null, caption: 'Checked in, camera charged, city calling. Where should I explore first?', tags: ['#Travel', '#CityNights', '#VirtualCreator'], createdAt: '2026-08-29T19:15:00Z', scheduledAt: '2026-09-01T18:00:00Z', publishState: 'scheduled', mediaType: 'video', sourceUrl: 'https://example.com/mila-hotel-lobby.mp4', performance: { note: 'Scheduled; performance will appear after a connected publisher sync.' } },
  { id: 'mv-004', title: 'Coffee and a side quest', brief: 'Adult virtual creator at a modern coffee shop with laptop and game controller. Warm lifestyle image with brunette hair, hazel-green eyes, subtle jewelry; non-explicit.', pillar: 'Lifestyle', status: 'approved', provider: 'Hugging Face', model: 'Flux', costUsd: 0.04, caption: 'Coffee first, then side quests. That is the rule ☕', tags: ['#CoffeeShop', '#Lifestyle', '#MilaVale'], createdAt: '2026-08-28T16:00:00Z', publishState: 'not_published', mediaType: 'image', performance: { note: 'Approved and ready to schedule.' } },
  { id: 'mv-005', title: 'After-hours tailoring', brief: 'Adult virtual creator in a modern city nightlife setting, sleek tailored fashion, warm ambient light, polished natural makeup; non-explicit fashion editorial.', pillar: 'Fashion', status: 'draft', provider: 'Higgsfield', model: 'Soul', costUsd: 0.18, caption: 'Outfit check before the city lights take over.', tags: ['#Fashion', '#NightOut', '#MilaVale'], createdAt: '2026-08-27T20:20:00Z', publishState: 'not_published', mediaType: 'image', performance: { note: 'Draft; send to QC before approval.' } },
]

export const connections: ProviderConnection[] = [
  { name: 'Fanvue', role: 'Publishing, account and performance sync', state: 'not_connected', detail: 'Awaiting verified application credentials and capability review.' },
  { name: 'Higgsfield', role: 'Preferred image, video and reference generation', state: 'not_connected', detail: 'Ready for secure API configuration or metadata imports.' },
  { name: 'Hugging Face', role: 'Secondary modular generation provider', state: 'not_connected', detail: 'No application token configured.' },
]
